/**
 * The colony's item content: rarities and the item set. Registered on demand,
 * never at top level (docs/GMRT.md).
 */
const RARITIES = [
  { id: "common", name: "RARITY_COMMON", color: "#b0b0b0", valueMod: 1 },
  { id: "uncommon", name: "RARITY_UNCOMMON", color: "#4caf50", valueMod: 2 },
  { id: "rare", name: "RARITY_RARE", color: "#2196f3", valueMod: 5 },
  { id: "epic", name: "RARITY_EPIC", color: "#9c27b0", valueMod: 12 },
  { id: "legendary", name: "RARITY_LEGENDARY", color: "#ff9800", valueMod: 30 },
];

globalThis.contentItems = {
  register() {
    Rarity.register(RARITIES);

    // `sprite` is the world and held art, shared freely between ids. A misspelt ref kills
    // the runner without a log (docs/GMRT.md).
    Item.register([
      // ---- consumables
      {
        id: "bandage",
        name: "ITEM_BANDAGE",
        description: "ITEM_BANDAGE_DESC",
        sprite: pixItemBandage,
        weight: 1,
        value: 3,
        rarity: "common",
        components: [new Consumable({ heal: 3 })],
      },
      {
        id: "ointment",
        name: "ITEM_OINTMENT",
        description: "ITEM_OINTMENT_DESC",
        sprite: pixItemOintment,
        weight: 1,
        value: 8,
        rarity: "common",
        components: [new Consumable({ status: "regen" })],
      },
      {
        id: "first_aid_kit",
        name: "ITEM_FIRST_AID_KIT",
        description: "ITEM_FIRST_AID_KIT_DESC",
        sprite: pixItemMedkit,
        weight: 2,
        value: 25,
        rarity: "uncommon",
        components: [new Consumable({ heal: 12 })],
      },
      {
        id: "water_bottle",
        name: "ITEM_WATER_BOTTLE",
        description: "ITEM_WATER_BOTTLE_DESC",
        sprite: pixItemWaterBottle,
        weight: 1,
        value: 4,
        rarity: "common",
        components: [new Consumable({ needs: { [Thirst]: 45 } })],
      },
      {
        id: "apple",
        name: "ITEM_APPLE",
        description: "ITEM_APPLE_DESC",
        sprite: pixItemApple,
        weight: 1,
        value: 2,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 15, [Thirst]: 5 } })],
      },
      {
        id: "energy_bar",
        name: "ITEM_ENERGY_BAR",
        description: "ITEM_ENERGY_BAR_DESC",
        sprite: pixItemEnergyBar,
        weight: 1,
        value: 4,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 25 } })],
      },
      {
        id: "soda",
        name: "ITEM_SODA",
        description: "ITEM_SODA_DESC",
        sprite: pixItemSoda,
        weight: 1,
        value: 5,
        rarity: "common",
        components: [new Consumable({ needs: { [Thirst]: 30 } })],
      },
      {
        id: "onigiri",
        name: "ITEM_ONIGIRI",
        description: "ITEM_ONIGIRI_DESC",
        sprite: pixItemOnigiri,
        weight: 1,
        value: 5,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 30 } })],
      },
      {
        id: "snack",
        name: "ITEM_SNACK",
        description: "ITEM_SNACK_DESC",
        sprite: pixItemSnack,
        weight: 1,
        value: 3,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 15 } })],
      },
      {
        id: "raw_meat",
        name: "ITEM_RAW_MEAT",
        description: "ITEM_RAW_MEAT_DESC",
        sprite: pixItemRawMeat,
        weight: 1,
        value: 3,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 10 } })],
      },
      {
        id: "cooked_meat",
        name: "ITEM_COOKED_MEAT",
        description: "ITEM_COOKED_MEAT_DESC",
        sprite: pixItemCookedMeat,
        weight: 1,
        value: 10,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 50 }, heal: 3 })],
      },
      {
        id: "canned_pork",
        name: "ITEM_CANNED_PORK",
        description: "ITEM_CANNED_PORK_DESC",
        sprite: pixItemPorkCan,
        weight: 1,
        value: 8,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 45 } })],
      },
      {
        id: "canned_tuna",
        name: "ITEM_CANNED_TUNA",
        description: "ITEM_CANNED_TUNA_DESC",
        sprite: pixItemTunaCan,
        weight: 1,
        value: 7,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 35, [Thirst]: 5 } })],
      },

      // ---- issue gear: the regular army's kit, one caliber per gun class
      {
        id: "service_pistol",
        name: "ITEM_SERVICE_PISTOL",
        description: "ITEM_SERVICE_PISTOL_DESC",
        sprite: pixItemPistol,
        weight: 2,
        value: 60,
        rarity: "uncommon",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 2 } }),
          new Weapon({ fireCd: 0.15 }),
          new Gun({ caliber: "pistol", magazine: 15 }),
        ],
      },
      {
        id: "service_assault_rifle",
        name: "ITEM_SERVICE_ASSAULT_RIFLE",
        description: "ITEM_SERVICE_ASSAULT_RIFLE_DESC",
        sprite: pixItemAssaultRifle,
        weight: 4,
        value: 150,
        rarity: "rare",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 3 } }),
          new Weapon({ fireCd: 0.1 }),
          new Gun({ caliber: "rifle", magazine: 30 }),
        ],
      },
      {
        id: "service_sniper_rifle",
        name: "ITEM_SERVICE_SNIPER_RIFLE",
        description: "ITEM_SERVICE_SNIPER_RIFLE_DESC",
        sprite: pixItemSniperRifle,
        weight: 6,
        value: 200,
        rarity: "rare",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 4 } }),
          new Weapon({ fireCd: 1.2 }),
          new Gun({ caliber: "sniper", magazine: 5 }),
        ],
      },
      {
        // a mounted gun's Armament: never carried, so nothing makes it equippable
        id: "light_machine_gun",
        name: "ITEM_LIGHT_MACHINE_GUN",
        description: "ITEM_LIGHT_MACHINE_GUN_DESC",
        sprite: pixItemAssaultRifle,
        weight: 12,
        value: 400,
        rarity: "rare",
        components: [
          new Weapon({ fireCd: 0.08 }),
          new Gun({ caliber: "rifle", magazine: 100 }),
        ],
      },
      // TODO: gear without an effect until the equipment pass
      {
        id: "tactical_headphones",
        name: "ITEM_TACTICAL_HEADPHONES",
        description: "ITEM_TACTICAL_HEADPHONES_DESC",
        sprite: pixItemHeadphones,
        weight: 1,
        value: 30,
        rarity: "uncommon",
      },
      {
        id: "pistol_ammo",
        name: "ITEM_PISTOL_AMMO",
        description: "ITEM_PISTOL_AMMO_DESC",
        sprite: pixItemAmmoPistol,
        weight: 0,
        value: 1,
        rarity: "common",
        components: [
          new Ammo({
            caliber: "pistol",
            mass: 3,
            velocity: 1200,
            power: 2,
            penetration: 1,
          }),
        ],
      },
      {
        id: "rifle_ammo",
        name: "ITEM_RIFLE_AMMO",
        description: "ITEM_RIFLE_AMMO_DESC",
        sprite: pixItemAmmoRifle,
        weight: 0,
        value: 2,
        rarity: "common",
        components: [
          new Ammo({
            caliber: "rifle",
            mass: 4,
            velocity: 1600,
            power: 3,
            penetration: 3,
          }),
        ],
      },
      {
        id: "sniper_ammo",
        name: "ITEM_SNIPER_AMMO",
        description: "ITEM_SNIPER_AMMO_DESC",
        sprite: pixItemAmmoSniper,
        weight: 0,
        value: 5,
        rarity: "uncommon",
        components: [
          new Ammo({
            caliber: "sniper",
            mass: 10,
            velocity: 1800,
            power: 6,
            penetration: 6,
          }),
        ],
      },
      {
        id: "he_grenade",
        name: "ITEM_HE_GRENADE",
        description: "ITEM_HE_GRENADE_DESC",
        sprite: pixItemGrenadeHe,
        weight: 1,
        value: 20,
        rarity: "uncommon",
        components: [new Throwable({ radius: 80, damage: 8 })],
      },
      {
        id: "frag_grenade",
        name: "ITEM_FRAG_GRENADE",
        description: "ITEM_FRAG_GRENADE_DESC",
        sprite: pixItemGrenadeFrag,
        weight: 1,
        value: 20,
        rarity: "uncommon",
        components: [new Throwable({ radius: 112, damage: 5 })],
      },

      // ---- common gear
      {
        id: "round_glasses",
        name: "ITEM_ROUND_GLASSES",
        description: "ITEM_ROUND_GLASSES_DESC",
        sprite: pixItemGlassesRound,
        weight: 0,
        value: 6,
        rarity: "common",
      },
      {
        id: "spanner",
        name: "ITEM_SPANNER",
        description: "ITEM_SPANNER_DESC",
        sprite: pixItemWrench,
        weight: 2,
        value: 10,
        rarity: "common",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 1 } }),
          new Weapon({
            damage: 4,
            fireCd: 0.35,
            hitbox: { width: 76, height: 24, xoffset: 38, yoffset: 0 },
          }),
        ],
      },
      {
        id: "iron_pipe",
        name: "ITEM_IRON_PIPE",
        description: "ITEM_IRON_PIPE_DESC",
        sprite: pixItemPipe,
        weight: 4,
        value: 8,
        rarity: "common",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 1 } }),
          new Weapon({
            damage: 3,
            fireCd: 0.3,
            hitbox: { width: 80, height: 24, xoffset: 40, yoffset: 0 },
          }),
        ],
      },
      {
        id: "kitchen_knife",
        name: "ITEM_KITCHEN_KNIFE",
        description: "ITEM_KITCHEN_KNIFE_DESC",
        sprite: pixItemKitchenKnife,
        weight: 1,
        value: 8,
        rarity: "common",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 1 } }),
          new Weapon({
            damage: 3,
            fireCd: 0.2,
            hitbox: { width: 72, height: 24, xoffset: 36, yoffset: 0 },
          }),
        ],
      },

      // ---- clothing: worn on the doll, one piece per slot
      {
        id: "shirt",
        name: "ITEM_SHIRT",
        description: "ITEM_SHIRT_DESC",
        sprite: pixItemShirt,
        weight: 1,
        value: 6,
        rarity: "common",
        components: [new Equippable({ slot: "body", worn: pixShirtBlue })],
      },
      {
        id: "pants",
        name: "ITEM_PANTS",
        description: "ITEM_PANTS_DESC",
        sprite: pixItemPants,
        weight: 1,
        value: 6,
        rarity: "common",
        components: [new Equippable({ slot: "legs", worn: pixPantsKhaki })],
      },
      {
        id: "beanie",
        name: "ITEM_BEANIE",
        description: "ITEM_BEANIE_DESC",
        sprite: pixItemBeanie,
        weight: 0,
        value: 8,
        rarity: "common",
        components: [new Equippable({ slot: "head", worn: pixHatBeanie })],
      },
      {
        id: "jungle_hat",
        name: "ITEM_JUNGLE_HAT",
        description: "ITEM_JUNGLE_HAT_DESC",
        sprite: pixItemJungleHat,
        weight: 0,
        value: 8,
        rarity: "common",
        components: [new Equippable({ slot: "head", worn: pixHatJungle })],
      },
      {
        id: "fedora",
        name: "ITEM_FEDORA",
        description: "ITEM_FEDORA_DESC",
        sprite: pixItemFedora,
        weight: 0,
        value: 15,
        rarity: "uncommon",
        components: [new Equippable({ slot: "head", worn: pixHatFedora })],
      },
      {
        id: "helmet",
        name: "ITEM_HELMET",
        description: "ITEM_HELMET_DESC",
        sprite: pixItemHelmet,
        weight: 2,
        value: 40,
        rarity: "uncommon",
        components: [
          new Equippable({ slot: "head", mods: { defense: 1 }, worn: pixHatHelmet }),
        ],
      },
      {
        id: "body_armor",
        name: "ITEM_BODY_ARMOR",
        description: "ITEM_BODY_ARMOR_DESC",
        sprite: pixItemBodyArmor,
        weight: 6,
        value: 120,
        rarity: "rare",
        components: [
          new Equippable({
            slot: "outer",
            mods: { defense: 2, maxHp: 5 },
            worn: pixOuterArmoredVest,
          }),
        ],
      },
      {
        id: "duster",
        name: "ITEM_DUSTER",
        description: "ITEM_DUSTER_DESC",
        sprite: pixItemDuster,
        weight: 3,
        value: 35,
        rarity: "uncommon",
        components: [new Equippable({ slot: "outer", worn: pixOuterDuster })],
      },
      {
        id: "work_gloves",
        name: "ITEM_WORK_GLOVES",
        description: "ITEM_WORK_GLOVES_DESC",
        sprite: pixItemGloves,
        weight: 1,
        value: 10,
        rarity: "common",
        components: [new Equippable({ slot: "hands", worn: pixGloveLeather })],
      },
      {
        id: "work_boots",
        name: "ITEM_WORK_BOOTS",
        description: "ITEM_WORK_BOOTS_DESC",
        sprite: pixItemBoots,
        weight: 2,
        value: 20,
        rarity: "common",
        components: [new Equippable({ slot: "feet", worn: pixShoeBoot })],
      },
      {
        id: "backpack",
        name: "ITEM_BACKPACK",
        description: "ITEM_BACKPACK_DESC",
        sprite: pixBackpack,
        weight: 2,
        value: 30,
        rarity: "uncommon",
        components: [
          new Equippable({ slot: "backpack", worn: pixBackpackBrown }),
          new Container({ bonusWeight: 20 }),
        ],
      },

      // ---- furniture: set down from the bag, one unit per placement
      // TODO: the placeholder draws in place of item art until furniture icons are authored
      {
        id: "crate",
        name: "ITEM_CRATE",
        weight: 3,
        value: 4,
        rarity: "common",
        components: [new Placeable({ build: "crate" })],
      },
      {
        id: "barrel",
        name: "ITEM_BARREL",
        weight: 3,
        value: 4,
        rarity: "common",
        components: [new Placeable({ build: "barrel" })],
      },
      {
        id: "bed",
        name: "ITEM_BED",
        weight: 8,
        value: 16,
        rarity: "common",
        components: [new Placeable({ build: "bed" })],
      },
      {
        id: "cot",
        name: "ITEM_COT",
        weight: 5,
        value: 10,
        rarity: "common",
        components: [new Placeable({ build: "cot" })],
      },
      {
        id: "table",
        name: "ITEM_TABLE",
        weight: 5,
        value: 8,
        rarity: "common",
        components: [new Placeable({ build: "table" })],
      },
      {
        id: "table_coffee",
        name: "ITEM_TABLE_COFFEE",
        weight: 4,
        value: 6,
        rarity: "common",
        components: [new Placeable({ build: "table_coffee" })],
      },
      {
        id: "table_small",
        name: "ITEM_TABLE_SMALL",
        weight: 3,
        value: 6,
        rarity: "common",
        components: [new Placeable({ build: "table_small" })],
      },
      {
        id: "dresser",
        name: "ITEM_DRESSER",
        weight: 6,
        value: 10,
        rarity: "common",
        components: [new Placeable({ build: "dresser" })],
      },
      {
        id: "dresser_double",
        name: "ITEM_DRESSER_DOUBLE",
        weight: 8,
        value: 14,
        rarity: "common",
        components: [new Placeable({ build: "dresser_double" })],
      },
      {
        id: "stool",
        name: "ITEM_STOOL",
        weight: 1,
        value: 2,
        rarity: "common",
        components: [new Placeable({ build: "stool" })],
      },
      {
        id: "stool_round",
        name: "ITEM_STOOL_ROUND",
        weight: 1,
        value: 2,
        rarity: "common",
        components: [new Placeable({ build: "stool_round" })],
      },
      {
        id: "nightstand",
        name: "ITEM_NIGHTSTAND",
        weight: 2,
        value: 4,
        rarity: "common",
        components: [new Placeable({ build: "nightstand" })],
      },
      {
        id: "torch",
        name: "ITEM_TORCH",
        weight: 1,
        value: 6,
        rarity: "common",
        components: [new Placeable({ build: "torch" })],
      },
      {
        id: "lantern",
        name: "ITEM_LANTERN",
        weight: 1,
        value: 12,
        rarity: "common",
        components: [new Placeable({ build: "lantern" })],
      },
      {
        id: "chest",
        name: "ITEM_CHEST",
        weight: 5,
        value: 10,
        rarity: "common",
        components: [new Placeable({ build: "chest" })],
      },
      {
        id: "workbench",
        name: "ITEM_WORKBENCH",
        weight: 10,
        value: 16,
        rarity: "common",
        components: [new Placeable({ build: "workbench" })],
      },
      {
        id: "medical_bench",
        name: "ITEM_MEDICAL_BENCH",
        weight: 10,
        value: 20,
        rarity: "common",
        components: [new Placeable({ build: "medical_bench" })],
      },
      {
        id: "cooking_bench",
        name: "ITEM_COOKING_BENCH",
        weight: 10,
        value: 20,
        rarity: "common",
        components: [new Placeable({ build: "cooking_bench" })],
      },
      {
        id: "machining_bench",
        name: "ITEM_MACHINING_BENCH",
        weight: 10,
        value: 28,
        rarity: "common",
        components: [new Placeable({ build: "machining_bench" })],
      },
      {
        id: "mod_bench",
        name: "ITEM_MOD_BENCH",
        weight: 10,
        value: 28,
        rarity: "common",
        components: [new Placeable({ build: "mod_bench" })],
      },
      {
        id: "turret",
        name: "ITEM_TURRET",
        weight: 12,
        value: 40,
        rarity: "common",
        components: [new Placeable({ build: "turret" })],
      },
      {
        id: "machine_gun_mount",
        name: "ITEM_MACHINE_GUN_MOUNT",
        weight: 15,
        value: 60,
        rarity: "common",
        components: [new Placeable({ build: "light_machine_gun" })],
      },
      {
        id: "watertank",
        name: "ITEM_WATERTANK",
        weight: 6,
        value: 8,
        rarity: "common",
        components: [new Placeable({ build: "watertank" })],
      },
      {
        id: "rationbox",
        name: "ITEM_RATIONBOX",
        weight: 4,
        value: 8,
        rarity: "common",
        components: [new Placeable({ build: "rationbox" })],
      },
      {
        id: "shrine",
        name: "ITEM_SHRINE",
        weight: 10,
        value: 24,
        rarity: "common",
        components: [new Placeable({ build: "shrine" })],
      },
      // ---- seeds: a crop set down as a seedling
      {
        id: "wheat_seed",
        name: "ITEM_WHEAT_SEED",
        weight: 0,
        value: 1,
        rarity: "common",
        components: [new Placeable({ build: "wheat" })],
      },
      {
        id: "berry_seed",
        name: "ITEM_BERRY_SEED",
        weight: 0,
        value: 2,
        rarity: "common",
        components: [new Placeable({ build: "berry_bush" })],
      },

      // ---- resources
      {
        id: "plank",
        name: "ITEM_PLANK",
        sprite: pixItemPlank,
        weight: 1,
        value: 1,
        rarity: "common",
        components: [new Material({ color: "#bb7547" })],
      },
      {
        id: "scrap_metal",
        name: "ITEM_SCRAP_METAL",
        sprite: pixItemScrapMetal,
        weight: 2,
        value: 4,
        rarity: "common",
        components: [new Material({ color: "#8b93af" })],
      },
      {
        id: "cloth",
        name: "ITEM_CLOTH",
        sprite: pixItemCloth,
        weight: 1,
        value: 2,
        rarity: "common",
      },
      {
        id: "tarp",
        name: "ITEM_TARP",
        sprite: pixItemTarp,
        weight: 2,
        value: 6,
        rarity: "common",
      },
      {
        id: "gold",
        name: "ITEM_GOLD",
        sprite: pixItemGold,
        weight: 1,
        value: 80,
        rarity: "rare",
      },
      {
        id: "diamond",
        name: "ITEM_DIAMOND",
        sprite: pixItemDiamond,
        weight: 0,
        value: 150,
        rarity: "epic",
      },

      // ---- junk: worth only what a trader pays
      {
        id: "blueprint",
        name: "ITEM_BLUEPRINT",
        description: "ITEM_BLUEPRINT_DESC",
        sprite: pixItemBlueprint,
        weight: 0,
        value: 15,
        rarity: "uncommon",
      },
      {
        id: "vinyl",
        name: "ITEM_VINYL",
        description: "ITEM_VINYL_DESC",
        sprite: pixItemVinyl,
        weight: 1,
        value: 20,
        rarity: "uncommon",
      },
      {
        id: "floppy_disk",
        name: "ITEM_FLOPPY_DISK",
        description: "ITEM_FLOPPY_DISK_DESC",
        sprite: pixItemFloppyDisk,
        weight: 0,
        value: 12,
        rarity: "uncommon",
      },

      // the currency; stacks high so a large balance occupies one slot
      {
        id: "coin",
        name: "ITEM_COIN",
        sprite: pixIconCoin,
        weight: 0,
        value: 1,
        rarity: "common",
        stack: 99999,
      },
    ]);
  },
};
