/**
 * The colony's item content: rarities, manufacturers and the item set. Registered on demand,
 * never at top level (docs/GMRT.md).
 */
const RARITIES = [
  { id: "common", name: "RARITY_COMMON", color: "#b0b0b0", valueMod: 1 },
  { id: "uncommon", name: "RARITY_UNCOMMON", color: "#4caf50", valueMod: 2 },
  { id: "rare", name: "RARITY_RARE", color: "#2196f3", valueMod: 5 },
  { id: "epic", name: "RARITY_EPIC", color: "#9c27b0", valueMod: 12 },
  { id: "legendary", name: "RARITY_LEGENDARY", color: "#ff9800", valueMod: 30 },
];

// A maker's `ops` is its signature weapon layer, folded in like an attachment — Aeon fast and
// precise but soft, Vekt slow but punchy with small clips. Helios makes survival gear.
const MAKERS = [
  {
    id: "aeon",
    name: "MAKER_AEON",
    lore: "MAKER_AEON_LORE",
    color: "#4dd0e1",
    ops: {
      fireCd: { mul: 0.8 },
      velocity: { mul: 1.15 },
      power: { mul: 0.9 },
      damage: { mul: 0.9 },
    },
  },
  {
    id: "vekt",
    name: "MAKER_VEKT",
    lore: "MAKER_VEKT_LORE",
    color: "#e08a3c",
    ops: {
      fireCd: { mul: 1.25 },
      power: { mul: 1.3 },
      damage: { mul: 1.3 },
      magazine: { mul: 0.75 },
    },
  },
  {
    id: "helios",
    name: "MAKER_HELIOS",
    lore: "MAKER_HELIOS_LORE",
    color: "#9ccc65",
  },
];

globalThis.contentItems = {
  register() {
    Rarity.register(RARITIES);
    Manufacturer.register(MAKERS);

    // `sprite` is the bag icon, shared freely between ids; a def without one has no icon art
    // yet. A misspelt ref kills the runner without a log (docs/GMRT.md).
    Item.register([
      {
        id: "rags",
        name: "ITEM_RAGS",
        sprite: pixItemRags,
        weight: 1,
        value: 2,
        rarity: "common",
      },
      {
        id: "medkit",
        name: "ITEM_MEDKIT",
        description: "ITEM_MEDKIT_DESC",
        sprite: pixItemMedkit,
        weight: 1,
        value: 10,
        rarity: "uncommon",
        components: [new Consumable({ heal: 5 })],
      },
      {
        id: "medgel",
        name: "ITEM_MEDGEL",
        description: "ITEM_MEDGEL_DESC",
        sprite: pixItemMedgel,
        weight: 1,
        value: 15,
        rarity: "uncommon",
        components: [new Consumable({ status: "regen" })],
      },
      {
        id: "combat_stim",
        name: "ITEM_COMBAT_STIM",
        description: "ITEM_COMBAT_STIM_DESC",
        sprite: pixItemCombatStim,
        weight: 1,
        value: 35,
        rarity: "rare",
        components: [new Consumable({ status: "fortify" })],
      },
      {
        id: "water_bottle",
        name: "ITEM_WATER_BOTTLE",
        description: "ITEM_WATER_BOTTLE_DESC",
        sprite: pixItemWaterBottle,
        weight: 1,
        value: 4,
        rarity: "common",
        components: [new Consumable({ needs: { [Thirst]: 45 } })],
      },
      {
        id: "soda",
        name: "ITEM_SODA",
        description: "ITEM_SODA_DESC",
        sprite: pixItemSoda,
        weight: 1,
        value: 6,
        rarity: "common",
        components: [new Consumable({ needs: { [Thirst]: 30 }, yields: "soda_trash" })],
      },
      {
        id: "soda_trash",
        name: "ITEM_SODA_TRASH",
        description: "ITEM_SODA_TRASH_DESC",
        sprite: pixItemSodaTrash,
        weight: 1,
        value: 1,
        rarity: "common",
      },
      {
        id: "ration_pack",
        name: "ITEM_RATION_PACK",
        description: "ITEM_RATION_PACK_DESC",
        sprite: pixItemCannedFood,
        weight: 1,
        value: 5,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 40 } })],
      },
      {
        id: "cooked_meat",
        name: "ITEM_COOKED_MEAT",
        description: "ITEM_COOKED_MEAT_DESC",
        sprite: pixItemCookedMeat,
        weight: 1,
        value: 12,
        rarity: "uncommon",
        components: [new Consumable({ needs: { [Hunger]: 60 }, heal: 3 })],
      },
      {
        id: "berries",
        name: "ITEM_BERRIES",
        description: "ITEM_BERRIES_DESC",
        sprite: pixItemApple,
        weight: 1,
        value: 3,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 20, [Thirst]: 5 } })],
      },
      {
        id: "grain",
        name: "ITEM_GRAIN",
        description: "ITEM_GRAIN_DESC",
        weight: 1,
        value: 2,
        rarity: "common",
        components: [new Consumable({ needs: { [Hunger]: 25 } })],
      },
      // item-driven progression instead of XP leveling
      {
        id: "power_serum",
        name: "ITEM_POWER_SERUM",
        description: "ITEM_POWER_SERUM_DESC",
        sprite: pixItemSerum,
        weight: 1,
        value: 50,
        rarity: "epic",
        components: [new Consumable({ attr: "pow", amount: 1 })],
      },
      {
        id: "vitality_serum",
        name: "ITEM_VITALITY_SERUM",
        description: "ITEM_VITALITY_SERUM_DESC",
        sprite: pixItemSerum,
        weight: 1,
        value: 50,
        rarity: "epic",
        components: [new Consumable({ attr: "vit", amount: 1 })],
      },
      {
        id: "agility_serum",
        name: "ITEM_AGILITY_SERUM",
        description: "ITEM_AGILITY_SERUM_DESC",
        sprite: pixItemSerum,
        weight: 1,
        value: 50,
        rarity: "epic",
        components: [new Consumable({ attr: "agi", amount: 1 })],
      },
      {
        id: "endurance_serum",
        name: "ITEM_ENDURANCE_SERUM",
        description: "ITEM_ENDURANCE_SERUM_DESC",
        sprite: pixItemSerum,
        weight: 1,
        value: 50,
        rarity: "epic",
        components: [new Consumable({ attr: "end", amount: 1 })],
      },
      {
        id: "lead_pipe",
        name: "ITEM_LEAD_PIPE",
        description: "ITEM_LEAD_PIPE_DESC",
        sprite: pixItemLeadPipe,
        weight: 4,
        value: 8,
        rarity: "common",
        components: [
          // no `worn`: drawn as its own icon at the doll's hand
          new Equippable({
            slot: "weapon",
            mods: { attack: 1 },
          }),
          new Weapon({
            damage: 3,
            fireCd: 0.3,
            hitbox: { width: 80, height: 24, xoffset: 40, yoffset: 0 },
            slots: [
              { id: "edge", accepts: "edge" },
              { id: "pommel", accepts: "pommel" },
            ],
          }),
        ],
      },
      {
        id: "blaster",
        name: "ITEM_BLASTER",
        description: "ITEM_BLASTER_DESC",
        sprite: pixItemPistol,
        weight: 5,
        value: 60,
        rarity: "rare",
        components: [
          new Equippable({
            slot: "weapon",
            mods: { attack: 2 },
          }),
          // neutral base: the attachments do the shaping
          new Weapon({
            fireCd: 0.13,
            slots: [
              { id: "scope", accepts: "scope" },
              { id: "barrel", accepts: "barrel" },
              { id: "magazine", accepts: "magazine" },
              { id: "grip", accepts: "grip" },
              { id: "muzzle", accepts: "muzzle" },
            ],
          }),
          new Gun({ caliber: "standard", magazine: 8 }),
        ],
      },
      {
        id: "armored_vest",
        name: "ITEM_ARMORED_VEST",
        description: "ITEM_ARMORED_VEST_DESC",
        // no icon of its own: the worn garment sheet, drawn fit-scaled
        sprite: pixOuterArmoredVest,
        weight: 8,
        value: 20,
        rarity: "uncommon",
        components: [
          new Equippable({
            slot: "armor",
            mods: { defense: 2, maxHp: 5 },
            worn: pixOuterArmoredVest,
          }),
        ],
      },
      {
        id: "adrenal_implant",
        name: "ITEM_ADRENAL_IMPLANT",
        sprite: pixItemEnergy,
        weight: 1,
        value: 40,
        rarity: "rare",
        components: [new Equippable({ slot: "trinket", mods: { speed: 80 } })],
      },
      // spares the wearer its seal's share of the open sky's exposure
      {
        id: "filter_mask",
        name: "ITEM_FILTER_MASK",
        description: "ITEM_FILTER_MASK_DESC",
        weight: 1,
        value: 25,
        rarity: "uncommon",
        components: [new Equippable({ slot: "trinket", seal: 0.75 })],
      },
      {
        id: "backpack",
        name: "ITEM_BACKPACK",
        sprite: pixItemBackpack,
        weight: 3,
        value: 30,
        rarity: "uncommon",
        components: [
          new Equippable({ slot: "backpack" }),
          new Container({ capacity: 8 }),
        ],
      },
      // stacks high so a large balance occupies one slot
      {
        id: "coin",
        name: "ITEM_COIN",
        sprite: pixItemCoinGold,
        weight: 0,
        value: 1,
        rarity: "common",
        stack: 99999,
      },
      {
        id: "circuitry",
        name: "ITEM_CIRCUITRY",
        weight: 1,
        value: 50,
        rarity: "rare",
      },
      {
        id: "keycard",
        name: "ITEM_KEYCARD",
        sprite: pixItemKeycard,
        weight: 0,
        value: 0,
        rarity: "epic",
      },
      {
        id: "wood",
        name: "ITEM_WOOD",
        sprite: pixItemWood,
        weight: 1,
        value: 1,
        rarity: "common",
        components: [new Material({ color: "#a9743f" })],
      },
      {
        id: "scrap_metal",
        name: "ITEM_SCRAP_METAL",
        sprite: pixItemScrapMetal,
        weight: 2,
        value: 4,
        rarity: "common",
        components: [new Material({ color: "#9aa3ad" })],
      },
      {
        id: "ammo_light",
        name: "ITEM_AMMO_LIGHT",
        description: "ITEM_AMMO_LIGHT_DESC",
        sprite: pixItemRounds,
        weight: 0,
        value: 1,
        rarity: "common",
        components: [
          new Ammo({
            caliber: "standard",
            mass: 3,
            velocity: 1440,
            power: 2,
            penetration: 1,
          }),
        ],
      },
      {
        id: "ammo_heavy",
        name: "ITEM_AMMO_HEAVY",
        description: "ITEM_AMMO_HEAVY_DESC",
        sprite: pixItemRounds,
        weight: 0,
        value: 2,
        rarity: "uncommon",
        components: [
          new Ammo({
            caliber: "standard",
            mass: 8,
            velocity: 960,
            power: 4,
            penetration: 3,
          }),
        ],
      },
      {
        id: "ammo_ap",
        name: "ITEM_AMMO_AP",
        description: "ITEM_AMMO_AP_DESC",
        sprite: pixItemRounds,
        weight: 0,
        value: 3,
        rarity: "uncommon",
        components: [
          new Ammo({
            caliber: "standard",
            mass: 5,
            velocity: 1200,
            power: 3,
            penetration: 6,
          }),
        ],
      },
      // attachment ops = (base+Σadd)·Πmul per field; inert on a field the weapon lacks
      {
        id: "mod_scope",
        name: "ITEM_MOD_SCOPE",
        description: "ITEM_MOD_SCOPE_DESC",
        sprite: pixItemModScope,
        weight: 1,
        value: 40,
        rarity: "rare",
        components: [
          new WeaponMod({
            slot: "scope",
            ops: { velocity: { add: 160 }, penetration: { add: 1 } },
          }),
        ],
      },
      {
        id: "mod_long_barrel",
        name: "ITEM_MOD_LONG_BARREL",
        description: "ITEM_MOD_LONG_BARREL_DESC",
        sprite: pixItemModLongBarrel,
        weight: 2,
        value: 35,
        rarity: "uncommon",
        components: [
          new WeaponMod({ slot: "barrel", ops: { velocity: { mul: 1.2 } } }),
        ],
      },
      {
        id: "mod_extended_mag",
        name: "ITEM_MOD_EXTENDED_MAG",
        description: "ITEM_MOD_EXTENDED_MAG_DESC",
        sprite: pixItemModExtendedMag,
        weight: 1,
        value: 30,
        rarity: "uncommon",
        components: [
          new WeaponMod({ slot: "magazine", ops: { magazine: { mul: 1.5 } } }),
        ],
      },
      {
        id: "mod_grip",
        name: "ITEM_MOD_GRIP",
        description: "ITEM_MOD_GRIP_DESC",
        sprite: pixItemModGrip,
        weight: 1,
        value: 30,
        rarity: "uncommon",
        components: [
          new WeaponMod({ slot: "grip", ops: { fireCd: { mul: 0.8 } } }),
        ],
      },
      {
        id: "mod_suppressor",
        name: "ITEM_MOD_SUPPRESSOR",
        description: "ITEM_MOD_SUPPRESSOR_DESC",
        sprite: pixItemModSuppressor,
        weight: 1,
        value: 45,
        rarity: "rare",
        components: [
          new WeaponMod({
            slot: "muzzle",
            ops: { velocity: { mul: 0.92 }, penetration: { add: 1 } },
          }),
        ],
      },
      {
        id: "mod_sharp",
        name: "ITEM_MOD_SHARP",
        description: "ITEM_MOD_SHARP_DESC",
        sprite: pixItemModSharp,
        weight: 1,
        value: 25,
        rarity: "uncommon",
        components: [
          new WeaponMod({
            slot: "edge",
            ops: { damage: { add: 2 } },
            stat: { attack: 1 },
          }),
        ],
      },
      {
        id: "mod_heavy",
        name: "ITEM_MOD_HEAVY",
        description: "ITEM_MOD_HEAVY_DESC",
        sprite: pixItemModHeavy,
        weight: 2,
        value: 40,
        rarity: "rare",
        components: [
          new WeaponMod({
            slot: "pommel",
            ops: { damage: { mul: 1.3 }, fireCd: { add: 0.07 } },
          }),
        ],
      },
      {
        id: "machining_module",
        name: "ITEM_MACHINING_MODULE",
        description: "ITEM_MACHINING_MODULE_DESC",
        sprite: pixItemMachiningModule,
        weight: 3,
        value: 30,
        rarity: "uncommon",
        components: [new WorkbenchModule()],
      },
      {
        id: "chem_module",
        name: "ITEM_CHEM_MODULE",
        description: "ITEM_CHEM_MODULE_DESC",
        sprite: pixItemChemModule,
        weight: 2,
        value: 35,
        rarity: "uncommon",
        components: [new WorkbenchModule()],
      },
      {
        id: "cooking_module",
        name: "ITEM_COOKING_MODULE",
        description: "ITEM_COOKING_MODULE_DESC",
        sprite: pixItemCookingModule,
        weight: 3,
        value: 25,
        rarity: "uncommon",
        components: [new WorkbenchModule()],
      },
      {
        id: "gunsmith_kit",
        name: "ITEM_GUNSMITH_KIT",
        description: "ITEM_GUNSMITH_KIT_DESC",
        sprite: pixItemGunsmithKit,
        weight: 2,
        value: 40,
        rarity: "rare",
        components: [new WorkbenchModule({ kind: "weaponmod" })],
      },
      // Branded gear: a maker's ops fold on top of the authored base, so two companies' takes on
      // the same weapon class play differently.
      // TODO: the pistols, the cutter, the ration and the rounds reuse base icons until they
      // get art of their own
      {
        id: "aeon_pistol",
        name: "ITEM_AEON_PISTOL",
        description: "ITEM_AEON_PISTOL_DESC",
        sprite: pixItemPistol,
        weight: 4,
        value: 85,
        rarity: "rare",
        maker: "aeon",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 2 } }),
          new Weapon({
            fireCd: 0.13,
            slots: [
              { id: "scope", accepts: "scope" },
              { id: "barrel", accepts: "barrel" },
              { id: "magazine", accepts: "magazine" },
              { id: "grip", accepts: "grip" },
              { id: "muzzle", accepts: "muzzle" },
            ],
          }),
          new Gun({ caliber: "standard", magazine: 10 }),
        ],
      },
      {
        id: "vekt_pistol",
        name: "ITEM_VEKT_PISTOL",
        description: "ITEM_VEKT_PISTOL_DESC",
        sprite: pixItemPistol,
        weight: 7,
        value: 85,
        rarity: "rare",
        maker: "vekt",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 3 } }),
          new Weapon({
            fireCd: 0.15,
            slots: [
              { id: "scope", accepts: "scope" },
              { id: "barrel", accepts: "barrel" },
              { id: "magazine", accepts: "magazine" },
              { id: "grip", accepts: "grip" },
              { id: "muzzle", accepts: "muzzle" },
            ],
          }),
          new Gun({ caliber: "standard", magazine: 8 }),
        ],
      },
      {
        id: "aeon_cutter",
        name: "ITEM_AEON_CUTTER",
        description: "ITEM_AEON_CUTTER_DESC",
        sprite: pixItemEnergy,
        weight: 3,
        value: 70,
        rarity: "rare",
        maker: "aeon",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 1 } }),
          new Weapon({
            damage: 3,
            fireCd: 0.2,
            hitbox: { width: 72, height: 24, xoffset: 36, yoffset: 0 },
            slots: [
              { id: "edge", accepts: "edge" },
              { id: "pommel", accepts: "pommel" },
            ],
          }),
        ],
      },
      {
        id: "vekt_wrench",
        name: "ITEM_VEKT_WRENCH",
        description: "ITEM_VEKT_WRENCH_DESC",
        sprite: pixItemVektWrench,
        weight: 6,
        value: 75,
        rarity: "rare",
        maker: "vekt",
        components: [
          new Equippable({ slot: "weapon", mods: { attack: 2 } }),
          new Weapon({
            damage: 5,
            fireCd: 0.4,
            hitbox: { width: 84, height: 24, xoffset: 42, yoffset: 0 },
            slots: [
              { id: "edge", accepts: "edge" },
              { id: "pommel", accepts: "pommel" },
            ],
          }),
        ],
      },
      {
        id: "helios_vest",
        name: "ITEM_HELIOS_VEST",
        description: "ITEM_HELIOS_VEST_DESC",
        sprite: pixOuterArmoredVest,
        weight: 7,
        value: 45,
        rarity: "rare",
        maker: "helios",
        components: [
          new Equippable({
            slot: "armor",
            mods: { defense: 3, maxHp: 8 },
            worn: pixOuterArmoredVest,
          }),
        ],
      },
      {
        id: "helios_trauma_kit",
        name: "ITEM_HELIOS_TRAUMA_KIT",
        description: "ITEM_HELIOS_TRAUMA_KIT_DESC",
        sprite: pixItemHeliosTraumaKit,
        weight: 1,
        value: 25,
        rarity: "rare",
        maker: "helios",
        components: [new Consumable({ heal: 12 })],
      },
      {
        id: "helios_ration",
        name: "ITEM_HELIOS_RATION",
        description: "ITEM_HELIOS_RATION_DESC",
        sprite: pixItemCannedFood,
        weight: 1,
        value: 12,
        rarity: "uncommon",
        maker: "helios",
        components: [new Consumable({ needs: { [Hunger]: 50, [Thirst]: 25 } })],
      },
      {
        id: "aeon_rounds",
        name: "ITEM_AEON_ROUNDS",
        description: "ITEM_AEON_ROUNDS_DESC",
        sprite: pixItemRounds,
        weight: 0,
        value: 4,
        rarity: "rare",
        maker: "aeon",
        components: [
          new Ammo({
            caliber: "standard",
            mass: 2,
            velocity: 1800,
            power: 2,
            penetration: 2,
          }),
        ],
      },
    ]);
  },
};
