/**
 * The chunked map's resident world STORE plus the entity sim-LOD. Takes a `generator` (content
 * provider — a ChunkGenerator, or anything matching the contract below) plus an injected
 * `opts.spawn` adapter for descriptors, and drives EntitySnapshot capture/restore as chunks cross
 * the SIM ring.
 *
 * pregenerate() (map build, behind the scene fade) generates EVERY in-bounds chunk record up
 * front — terrain/walls/spawns are resident for the map's lifetime, generate() never runs
 * mid-game, and materialAt/costAt read stored terrain instead of re-sampling noise (TerrainStream
 * apron, NavGrid weights, PathFollow pricing).
 *
 * update() drives the two-state entity sim-LOD (Chebyshev chunk distance from the player's chunk):
 *   d <= simRadius → SIM:    entities live in the store, walls have colliders, sims + renders.
 *   d >  simRadius → FROZEN: entities held as EntitySnapshots ONCE they've been sim'd (drawn
 *                            statically by RenderChunks) — so modified entities persist and a
 *                            revisit restores them; a chunk not yet reached keeps only dormant
 *                            spawn DESCRIPTORS and does no store work until it first promotes.
 * Colliders exist only in SIM chunks: live bodies can't reach a frozen chunk, so its colliders
 * would be dead weight in every per-tick collider walk (SolidSystem/NavGrid/Raycast).
 *
 * The squad (player + hired companions) is never chunk-managed — only chunk-spawned content +
 * terrain colliders.
 *
 * generator contract (ChunkGenerator satisfies it):
 *   generator.generate(cx, cy) -> { walls: [[gx,gy,wCells,hCells]...]  (ABSOLUTE grid coords),
 *                                   solid?: [[gx,gy,wCells,hCells]...]  (collide-only rects, e.g. water — not drawn),
 *                                   spawns: [descriptor...],            (deterministic per cx,cy)
 *                                   terrain?: Int[]  per-cell material grid (cosmetic; TerrainStream) }
 *   generator.palette  (field, optional) — material table (pathCost per id; costAt + TerrainStream)
 *   generator.materialAt / costAt (optional) — pure samplers, the out-of-store fallback (only the
 *     render apron past the world edge reaches them)
 *   opts.spawn(entities, grid, descriptor) -> entityId  — the descriptor adapter (e.g. wraps
 *     RpgSpawn.spawnEntity); required only when chunks carry spawns
 * GMRT-safe: record maps walked via Object.keys + index loops (no Map/Set iteration).
 */
globalThis.ChunkManager = class ChunkManager {
  /**
   * opts: spawn (descriptor → entity adapter), chunkCols/chunkRows (cell size, default 16),
   * simRadius (ring distance, default 1), worldCols/worldRows (REQUIRED finite bounds anchored
   * at 0 — the world is a fixed rectangle of chunks, wholly generated by pregenerate()).
   */
  constructor(entities, grid, generator, opts = {}) {
    if (opts.worldCols === undefined || opts.worldRows === undefined)
      throw new Error("ChunkManager needs finite worldCols/worldRows");
    this.entities = entities;
    this.grid = grid;
    this.generator = generator;
    this._spawn = opts.spawn ?? null;
    this.chunkCols = opts.chunkCols ?? 16;
    this.chunkRows = opts.chunkRows ?? 16;
    this.simRadius = opts.simRadius ?? 1;

    // maxC* is the last in-bounds chunk index of the [0,worldCols)x[0,worldRows) rectangle
    this.maxCx = Math.floor((opts.worldCols - 1) / this.chunkCols);
    this.maxCy = Math.floor((opts.worldRows - 1) / this.chunkRows);

    this.cellW = grid.cellWidth;
    this.cellH = grid.cellHeight;
    this.pxW = this.chunkCols * this.cellW;
    this.pxH = this.chunkRows * this.cellH;

    // material table for the store-backed costAt (mirrors TerrainField's pathCost mapping);
    // absent on a palette-less generator → costAt delegates to the generator
    this._palette = generator.palette;

    // every in-bounds chunk record, keyed "cx,cy" → { cx, cy, ring, walls, solid, terrain,
    //   spawns, colliders, entities, snapshots, hydrated } — filled by pregenerate()
    this._chunks = {};
    // last player chunk — fast-path skips the ring walk until a border is crossed
    this._pcx = undefined;
    this._pcy = undefined;
  }

  /** Drop refs; the store owns the entities/colliders and frees them itself. */
  destroy() {
    this._chunks = {};
  }

  _key(cx, cy) {
    return cx + "," + cy;
  }
  chunkX(wx) {
    return Math.floor(wx / this.pxW);
  }
  chunkY(wy) {
    return Math.floor(wy / this.pxH);
  }

  /**
   * Re-ring the entity sim-LOD around a center (usually the player) — call once per frame,
   * OUTSIDE the tick loop. Returns early until the center crosses into a new chunk (ring
   * membership only changes then).
   */
  update(centerX, centerY) {
    const pcx = this.chunkX(centerX);
    const pcy = this.chunkY(centerY);
    const moved = pcx !== this._pcx || pcy !== this._pcy;
    this._pcx = pcx;
    this._pcy = pcy;

    if (moved) {
      const keys = Object.keys(this._chunks);
      for (let i = 0; i < keys.length; i++) {
        const rec = this._chunks[keys[i]];
        const d = Math.max(Math.abs(rec.cx - pcx), Math.abs(rec.cy - pcy));
        if (d <= this.simRadius) {
          if (rec.ring !== "sim") this._promote(rec);
        } else if (rec.ring === "sim") this._demote(rec);
      }

      // commit removals so demoted entities aren't double-drawn this frame
      this.entities.flush();
    }
  }

  /**
   * Whole-world WALL occupancy as a read-only layer view (`{ get(gx, gy) → bool }`, absolute
   * cells) — the `layer` a RenderWalls pass takes, so generated/authored walls draw as the same
   * lit boxes as a resident wall TileLayer. Walls never change in-session, so the cell set is
   * rasterized ONCE on first get() and cached for the manager's lifetime. (`solid` rects —
   * water — are collide-only and stay excluded, exactly like RenderChunks.)
   */
  wallLayer() {
    const mgr = this;
    return {
      _cells: null,
      get(gx, gy) {
        if (this._cells === null) this._cells = mgr._rasterizeWalls();
        return this._cells[gx + "," + gy] === true;
      },
    };
  }

  /** Every record's wall rects — the whole world after pregenerate(). */
  _rasterizeWalls() {
    const cells = {};
    const keys = Object.keys(this._chunks);
    for (let i = 0; i < keys.length; i++) {
      const walls = this._chunks[keys[i]].walls;
      for (let j = 0; j < walls.length; j++) {
        const r = walls[j];
        for (let dy = 0; dy < r[3]; dy++)
          for (let dx = 0; dx < r[2]; dx++)
            cells[r[0] + dx + "," + (r[1] + dy)] = true;
      }
    }
    return cells;
  }

  records() {
    const out = [];
    const keys = Object.keys(this._chunks);
    for (let i = 0; i < keys.length; i++) out.push(this._chunks[keys[i]]);
    return out;
  }

  // ── disk persistence (the "deep" save) ──
  // walls/solid/terrain/spawns are DETERMINISTIC from the seed (pregenerate regenerates them
  // identically), so a save serializes only the ENTITY-STATE DELTA of chunks that have been
  // touched: which mobs are dead/moved/hurt, what loot dropped. Untouched (hydrated:false) chunks
  // are skipped entirely — they come back from generate(). Import runs after pregenerate(), before
  // the first update(), so each restored chunk materializes its saved snapshots instead of fresh
  // spawns.

  /**
   * Every live SIM-ring entity id the manager owns — the caller excludes these from its own store
   * export so they aren't saved twice (they ride the chunk delta instead).
   */
  entityIds() {
    const out = [];
    const keys = Object.keys(this._chunks);
    for (let i = 0; i < keys.length; i++) {
      const ents = this._chunks[keys[i]].entities;
      for (let j = 0; j < ents.length; j++) out.push(ents[j]);
    }
    return out;
  }

  /**
   * Serialize the entity-state delta of every hydrated chunk. A SIM chunk's live entities are
   * captured NON-destructively (the game continues); a frozen chunk already holds snapshots.
   * `exclude` drops runtime-rebuilt components (PrevPosition/Path*) from each snapshot. A hydrated
   * chunk with zero entities is still recorded (the player cleared it — it must stay clear on
   * load, not repopulate from seed).
   */
  exportCache(exclude = []) {
    const filtered = (comps) => {
      const out = {};
      const toks = Object.keys(comps);
      for (let i = 0; i < toks.length; i++)
        if (exclude.indexOf(toks[i]) === -1) out[toks[i]] = comps[toks[i]];
      return out;
    };
    const out = [];
    const keys = Object.keys(this._chunks);
    for (let i = 0; i < keys.length; i++) {
      const rec = this._chunks[keys[i]];
      if (!rec.hydrated) continue; // untouched → regenerates identically
      const snaps = [];
      if (rec.ring === "sim") {
        for (let j = 0; j < rec.entities.length; j++)
          if (this.entities.isValid(rec.entities[j]))
            snaps.push({
              components: filtered(this.entities.componentsOf(rec.entities[j])),
            });
      } else {
        for (let j = 0; j < rec.snapshots.length; j++)
          snaps.push({ components: filtered(rec.snapshots[j].components) });
      }
      out.push({ cx: rec.cx, cy: rec.cy, snaps });
    }
    return out;
  }

  /**
   * Overwrite pregenerated records with a saved entity-state delta — call AFTER pregenerate() and
   * BEFORE the first update(), so each saved chunk materializes its snapshots (not fresh spawns).
   * Chunks absent from the save keep their generated spawns (untouched terrain, unmet mobs).
   */
  importCache(list) {
    if (list === undefined) return;
    for (let i = 0; i < list.length; i++) {
      const e = list[i];
      const rec = this._chunks[this._key(e.cx, e.cy)];
      if (rec === undefined) continue; // out of bounds
      rec.snapshots = e.snaps;
      rec.entities = [];
      rec.hydrated = true; // _materialize now restores snapshots instead of spawning descriptors
    }
  }

  // A chunk's entity state has three forms: DESCRIPTORS (rec.spawns, not yet materialized —
  // hydrated:false), LIVE (rec.entities in the store — SIM ring), or SNAPSHOTS (rec.snapshots —
  // frozen after a demote). `hydrated` marks "descriptors have become live/snapshots at least
  // once", so we never spawn a chunk we don't sim.

  /**
   * Generate EVERY in-bounds chunk record NOW (map build time, behind the scene fade) — after
   * this the records ARE the world and mid-game work is entity promote/demote only. Idempotent —
   * existing records keep their (possibly modified) state, so a resume/second call can't wipe
   * live state.
   */
  pregenerate() {
    let n = 0;
    for (let cy = 0; cy <= this.maxCy; cy++) {
      for (let cx = 0; cx <= this.maxCx; cx++) {
        const key = this._key(cx, cy);
        if (this._chunks[key] !== undefined) continue;
        const gen = this.generator.generate(cx, cy);
        this._chunks[key] = {
          cx,
          cy,
          ring: "frozen",
          walls: gen.walls, // [[gx,gy,w,h]...] absolute coords — wallLayer + render
          solid: gen.solid ?? [], // collide-only rects — meshed in SIM, NOT rendered
          terrain: gen.terrain, // per-cell material grid — TerrainStream renders it
          spawns: gen.spawns ?? [], // dormant descriptors until first sim (hydrated:false)
          colliders: [],
          entities: [],
          snapshots: [],
          hydrated: false,
        };
        n++;
      }
    }
    return n;
  }

  // store-backed terrain samplers — read the material a cell was GENERATED with; out-of-store
  // coords (the render apron past the world edge) fall back to the generator's pure sampler.

  materialAt(ax, ay) {
    const m = this._storedMaterial(ax, ay);
    if (m !== undefined) return m;
    return this.generator.materialAt !== undefined
      ? this.generator.materialAt(ax, ay)
      : 0;
  }

  costAt(ax, ay) {
    const m = this._storedMaterial(ax, ay);
    if (m !== undefined && this._palette !== undefined) {
      const c = this._palette[m].pathCost; // mirrors TerrainField.costAt's mapping
      return c === null ? Infinity : c;
    }
    return this.generator.costAt !== undefined
      ? this.generator.costAt(ax, ay)
      : 1;
  }

  _storedMaterial(ax, ay) {
    const cx = Math.floor(ax / this.chunkCols);
    const cy = Math.floor(ay / this.chunkRows);
    const rec = this._chunks[this._key(cx, cy)];
    if (rec === undefined || rec.terrain === undefined) return undefined;
    const lx = ax - cx * this.chunkCols;
    const ly = ay - cy * this.chunkRows;
    return rec.terrain[ly * this.chunkCols + lx];
  }

  _promote(rec) {
    this._meshColliders(rec);
    if (rec.hydrated) {
      this._restoreAll(rec, rec.snapshots);
      rec.snapshots = [];
    } else {
      this._spawnAll(rec, rec.spawns);
      rec.hydrated = true;
    }
    rec.ring = "sim";
  }

  _demote(rec) {
    this._captureAll(rec);
    this._dropColliders(rec);
    rec.ring = "frozen";
  }

  /**
   * One kinematic-solid collider per wall + solid rect (source already groups cells into rects).
   * Matches TileEdit.meshSolid: Position at rect top-left, BBox (0,0) spanning it.
   */
  _meshColliders(rec) {
    this._meshRects(rec, rec.walls);
    this._meshRects(rec, rec.solid);
  }

  _meshRects(rec, rects) {
    if (rects === undefined) return;
    const cw = this.cellW;
    const ch = this.cellH;
    const entities = this.entities;
    for (let i = 0; i < rects.length; i++) {
      const r = rects[i];
      const id = entities.create();
      entities.add(id, Position, { x: r[0] * cw, y: r[1] * ch, z: 0 });
      entities.add(id, BBox, {
        x: 0,
        y: 0,
        width: r[2] * cw,
        height: r[3] * ch,
      });
      entities.add(id, Collision, {
        solid: true,
        kinematic: true,
        mask: null,
        hits: [],
      });
      rec.colliders.push(id);
    }
  }

  _dropColliders(rec) {
    for (let i = 0; i < rec.colliders.length; i++)
      this.entities.remove(rec.colliders[i]);
    rec.colliders = [];
  }

  _spawnAll(rec, spawns) {
    if (spawns.length === 0) return;
    if (this._spawn === null)
      throw new Error(
        "ChunkManager: chunk has spawns but no opts.spawn adapter",
      );
    for (let i = 0; i < spawns.length; i++) {
      const id = this._spawn(this.entities, this.grid, spawns[i]);
      if (id !== undefined && id !== -1) rec.entities.push(id);
    }
  }

  _restoreAll(rec, snapshots) {
    for (let i = 0; i < snapshots.length; i++)
      rec.entities.push(EntitySnapshot.restore(this.entities, snapshots[i]));
  }

  /** Skips invalid ids (e.g. killed enemies) so the dead stay dead. */
  _captureAll(rec) {
    const snaps = [];
    for (let i = 0; i < rec.entities.length; i++) {
      const id = rec.entities[i];
      if (!this.entities.isValid(id)) continue;
      snaps.push(EntitySnapshot.capture(this.entities, id));
      this.entities.remove(id);
    }
    rec.entities = [];
    rec.snapshots = snaps;
  }
};
